import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "../globals.css";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <div className="min-h-screen">
        <header className="flex justify-end items-center p-4 gap-4 h-16">
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <UserButton afterSignOutUrl="/" />
        </header>
        <main>{children}</main>
      </div>
    </ClerkProvider>
  );
}
